package food.main;

import food.model.FoodOrder;
import food.model.PremiumOrder;
import food.model.RegularOrder;
import food.service.OrderService;
import food.utility.OrderUtility;

/**
 * Driver program for the Online Food Delivery application.
 * Creates six food orders, stores them in an array of FoodOrder,
 * validates each one, and displays the full bill (amount, discount,
 * delivery charge, final payable amount) for every order.
 */
public class Main {

    public static void main(String[] args) {

        // ---- i & ii: create at least six orders, stored via array of FoodOrder ----
        FoodOrder[] orders = new FoodOrder[6];
        orders[0] = new RegularOrder(101, "Aman Sharma", 500.0);
        orders[1] = new PremiumOrder(102, "Priya Verma", 1200.0);
        orders[2] = new RegularOrder(103, "Rohit Singh", 750.0);
        orders[3] = new PremiumOrder(104, "Sneha Kapoor", 950.0);
        orders[4] = new RegularOrder(105, "Karan Mehta", 300.0);
        orders[5] = new PremiumOrder(106, "Anita Desai", 1500.0);

        OrderService orderService = new OrderService();

        System.out.println("=====================================================");
        System.out.println("   " + FoodOrder.getRestaurantName() + " - ONLINE FOOD ORDERS");
        System.out.println("=====================================================");

        for (FoodOrder order : orders) {

            // Validate the order's data using OrderUtility before processing it
            if (!OrderUtility.validateAmount(order.getAmount())) {
                System.out.println("Skipping Order ID " + order.getOrderId()
                        + " -> invalid amount.");
                continue;
            }
            if (!OrderUtility.validateCustomerName(order.getCustomerName())) {
                System.out.println("Skipping Order ID " + order.getOrderId()
                        + " -> invalid customer name.");
                continue;
            }

            // iii, iv, v, vi: display bill, discount, delivery charge, final payable amount
            orderService.displayBill(order);

            // Print the one-line order summary generated by OrderUtility
            System.out.println(OrderUtility.generateOrderSummary(
                    order.getOrderId(), order.getCustomerName(),
                    order.getOrderType(), order.getAmount()));
            System.out.println();
        }

        // Static method that reports how many FoodOrder objects were created
        FoodOrder.displayTotalOrders();
    }
}
